/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    2: typeof import('./src/components/Chat copy 2.vue')['default']
    button: typeof import('./src/components/Chat copy 2 - toggle button.vue')['default']
    Chat: typeof import('./src/components/Chat.vue')['default']
    copy: typeof import('./src/components/Chat copy.vue')['default']
  }
}
